import { contextBridge, ipcRenderer } from 'electron';

contextBridge.exposeInMainWorld('fly', {
  onAmbient: (cb) => ipcRenderer.on('ambient', (_e, d) => cb(d)),
  onIcons: (cb) => ipcRenderer.on('icons', (_e, d) => cb(d)),
  onCmd: (cb) => ipcRenderer.on('cmd', (_e, d) => cb(d)),
  onSwatter: (cb) => ipcRenderer.on('swatter', (_e, d) => cb(d)),
  onRag: (cb) => ipcRenderer.on('rag', (_e, d) => cb(d)),
  onNet: (cb) => ipcRenderer.on('net', (_e, d) => cb(d)),
  onBottle: (cb) => ipcRenderer.on('bottle', (_e, d) => cb(d)),
  sendBottle: (s) => ipcRenderer.send('bottle', s),
  onSwatterMove: (cb) => ipcRenderer.on('swatter-move', (_e, d) => cb(d)),
  onRetarget: (cb) => ipcRenderer.on('retarget', (_e, d) => cb(d)),
  putAway: () => ipcRenderer.send('swatter-off'),
  sendLife: (s) => ipcRenderer.send('life-stats', s),
  sendSnapshot: (s) => ipcRenderer.send('snapshot', s),
  fanfare: (on) => ipcRenderer.send('fanfare', !!on),
  signIn: (email, password) => ipcRenderer.invoke('fly-signin', { email, password }),
  signOut: () => ipcRenderer.invoke('fly-signout'),
  currentUser: () => ipcRenderer.invoke('fly-current-user'),
  spawnFly: () => ipcRenderer.invoke('fly-spawn'),
  breed: (a, b) => ipcRenderer.invoke('fly-breed', { a, b }),
  submitRecord: (timeMs) => ipcRenderer.invoke('fly-submit-record', { timeMs }),
  submitMutation: (flyId) => ipcRenderer.invoke('fly-submit-mutation', { flyId }),
  addPoint: (n) => ipcRenderer.invoke('fly-add-point', { n }),
  createListing: (kind, flyIds, note, want, instar, color) => ipcRenderer.invoke('fly-create-listing', { kind, flyIds, note, want, instar, color }),
  unlistListing: (id) => ipcRenderer.invoke('fly-unlist-listing', { id }),
  createOffer: (listingId, kind, flyIds, note, color, instar) => ipcRenderer.invoke('fly-create-offer', { listingId, kind, flyIds, note, color, instar }),
});
